### ISSUE TITLE
Optional features

### ISSUE THREAD

**Issue by SeimeU** [Koracs/GoGame#32]
- [ ] multilingual implementation
- [ ] implementation with different rulesets
- [ ] game timer and player timer
- [ ] customizable UI
- [ ] statistics of the game
- [ ] background music
- [ ] reset last move
- [ ] live scoreboard
- [ ] home screen
- [ ] win screen
- [ ] implement avatars
- [ ] implement ki to play agains
